### PR TITLE
Add function for seeking time in iOS control center and lockscreen

### LINKED ISSUE #60: iOS: notifications/lock-screen time elapsed issue
Hey everyone,

The elapsed time on the iOS controls keep goes out of sync. Everytime you hit pause it goes back to zero. I've seen other apps using this plugin and they too have simply ignored sending time information to the plugin, which works fine in the notifications area (as iOS hides the time bar) but in the lockscreen it shows an ugly empty time bar.

Is there a way to fix this functionality? If not then is there a way to hide the time bar on the lockscreen?

Your help would be greatly appreciated.

(Angular 1.5, Ionic 1.3.2)

Cheers!

### PR DESCRIPTION
**Pull request by BuddyLReno**
This commit adds support for scrubbing with the progress bar on iOS' control center and lockscreen.  This fixes #60 and #61.

Ionic Native PR: https://github.com/ionic-team/ionic-native/pull/1727

- New event: `music-controls-seek-to`
- New function: `MusicControls.updateElapsed(args: object);`

*THIS IS A BREAKING CHANGE* (probably needs to update to 2.0.0 with this)

- Change: messages are now returned as json and need to be parsed. 
  `JSON.parse(action) === { message: "music-controls-next" }`
  
This is due to the fact that we need to get the new position of the audio file after the user has scrubbed with the iOS scrubber. Seconds are returned by iOS:

`JSON.parse(action) === { message: "music-controls-seek-to", position: "208" }` 
The position param returned by the `music-controls-seek-to` event is in seconds.

### CODE REVIEW

**Comment by homerours** [comment]
Thank you @BuddyLReno ! It looks good :) (However, I have no iOS device to test it...)
The Json messaging system was a needed evolution, everything is fine.

**Comment by BuddyLReno** [comment]
No problem @homerours! I've been using the new function with success in my company's iOS app streaming mp3's from libsyn. Should the version number be bumped? If someone updates to this version of the plugin, their implementation will break.

**Comment by BuddyLReno** [comment]
Also haven't heard from Ionic about the [ionic native PR](https://github.com/ionic-team/ionic-native/pull/1727) I placed at the same time to add this function.

**Comment by homerours** [comment]
Ok great! I going to update the version number. And if in the future you would like to add some more updates, I can grant you the "writing rights" on this project.

**Comment by BuddyLReno** [comment]
@homerours Totally! I'd love to continue to contribute. 👍

**Pull request merged**
