### PR TITLE
Added Android custom icon support

### PR DESCRIPTION
**Pull request by darthdie**
You can now supply the name of custom icons for play, pause, prev, next, close, and the general notification icon (in place of the play/pause icon).

E.g. in options:
{
  ...,
  playIcon: 'media_play',
  ...
}

### CODE REVIEW

**Comment by BuddyLReno** [comment]
Hello! This looks pretty good, can you rebase into a single commit?  Thanks :)

**Comment by darthdie** [comment]
Alright, I believe that's done. Full disclosure, I've never actually done a rebase to merge commits into one before.

**Comment by BuddyLReno** [comment]
I'll pull it down and see if It's registering correctly. It looks like there's new commits but that could just be github being weird.

**Comment by BuddyLReno** [comment]
closing in favor of using #99 (I was able to squash the commits)

**Pull request closed without merging**
