### PR TITLE
Add close button

### PR DESCRIPTION
**Pull request by alisonmonteiro**
Adding the button to close the notification bar and "organizing" the indent style of javascript file. @homerours

### CODE REVIEW

**Comment by homerours** [comment]
Thank you I merged that! I also added a new option: "dismissable" allow the user to swipe the notification to destroy it.

**Comment by alisonmonteiro** [comment]
Good @homerours :+1: 
I think is possible to add some action buttons when the screen is locked. ([example](http://www.androidpolice.com/wp-content/uploads/2014/06/nexusae0_Screenshot_2014-06-26-14-10-33.png))
I'm not good with Java but I like that. So I'm searching some solutions to add this feature in this repo!

**Comment by homerours** [comment]
I have searched for that in the SDK but did not find anything to add extra button on the lockscreen... What kind of buttons are you looking for ?

**Comment by alisonmonteiro** [comment]
Something like play/pause or next. [See an example](http://www.androidpolice.com/wp-content/uploads/2014/06/nexusae0_Screenshot_2014-06-26-14-10-33.png)

**Comment by homerours** [comment]
Ok, I just added this !

**Comment by alisonmonteiro** [comment]
Thank you!

**Pull request merged**
