### PR TITLE
Updated 'UpdateIsPlaying' to avoid reacreating the whole notification

### PR DESCRIPTION
**Pull request by igor9silva**

### CODE REVIEW

**Comment by homerours** [comment]
Nice pull request !
However, I'm experiencing some issues with it:
- the `Notification.Action` class is only available for SDK Version >= 19 (Android 4.4)
- the `Notification.builder.addAction` method is available for SDK Version >= 20 ('KitKat Watch', so Lolipop for smartphones...)
That's why it does'nt work on my Android 4.4... Moreover, I would like to keep supporting Android 4.1 (SDK 16).

For Lollipop devices, your PR is *the good way to update the play pause button*, but for older Android version I see no other solution than recreating the notification each time playplause is called... A solution (compatible for all versions) could be to keep a `Bitmap` object inside of the `MusicControlsNotification` object, in order to avoid to download it again...

What do you think about this?

**Comment by igor9silva** [comment]
Yes, would be a good solution.
I only noticed that it's not compatible with 4.1+ 5 minutes before leaving the office. Will look into that again tomorrow.

In a soon future I'll work on a plugin to create a notification like that but using RemoteViews (custom view), since the native API lacks important features like a quit button (an 'x' on right-top, like Spotify's).

**Comment by filfat** [comment]
@igor9silva +1 for RemoteViews ;)

**Comment by 0505gonzalez** [comment]
@igor9silva Friendly nudge, would be great if we can get your PR merged :)

**Comment by BuddyLReno** [comment]
@homerours @igor9silva @0505gonzalez Now that 4.1 is quite old, do we still see it as necessary to keep support for it? 8.0 is out so those devices are probably _very_ old. I'd like to merge or close this PR. Trying to clean up the outstanding issues/prs.

**Comment by igor9silva** [comment]
@BuddyLReno I'd that it is still important to keep supporting 4.1, at least for a few more months.

Of course it depends on your project specific needs, but since this one is generic and that, according to Google itself, 6.6% of users are still using 4.1~4.3 (see [Android Dashboard](https://developer.android.com/about/dashboards/index.html)).

It is even worse on some poor/emerging countries, like Brazil, India and most of Africa.

**Pull request closed without merging**
