### PR TITLE
Added support for custom icons in android.

### PR DESCRIPTION
**Pull request by BuddyLReno**
@darthdie I pulled your fork and reworked the commits to be a single commit. Can you verify that this branch still works?

### CODE REVIEW

**Comment by darthdie** [comment]
Yup, working well on my end. Apologies for the commit trouble, thanks for the help

**Comment by shawns582** [comment]
@BuddyLReno @darthdie can one of you please give some instructions on how to get this working on android? I have placed a notification.png in the platforms/android/res/drawables* folders and passed notificationIcon: 'notification' in the MusicControls.create() function.

I had previously used this same image when I manually changed the Java code before this notificationIcon was added. It was working then. However now it is for some reason not working. Anything else I need to do to register the drawable? thanks

**Comment by shawns582** [comment]
nm looks like I got it working by adding resource tags to my config.xml in my Ionic app:
For example I did this for each drawable folder

<platform name="android">
<resource-file src="resources/android/ic_notification_small.png" target="app/src/main/res/drawable-mdpi/ic_notification_small.png" />
...
</platform>

**Comment by julianCast** [comment]
So,...any instructions? Thanks!

**Pull request merged**
